language: node_js
cache: yarn
node_js:
  - "node"
before_install:
  - npm install -g yarn
install:
  - cd frontend && yarn install
script:
  - cd frontend && npm run build
deploy:
  skip_cleanup: true
