language: node_js
cache: yarn
pyton: 3.7
node_js:
- node
before_install:
- cd frontend
install:
- yarn install
- npm install -g yarn
- pip install awscli
script:
- npm run build
deploy:
  skip_cleanup: true
  provider: s3
  access_key_id: "$AWS_ACCESS_KEY_ID"
  secret_access_key: "$AWS_SECRET_ACCESS_KEY"
  bucket: hydra.wildbit.com
  local_dir: build
  acl: public_read
  on:
    tags: true
after_deploy:
- aws configure set preview.cloudfront true
- aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DISTRIBUTION_ID
env:
  global:
  - secure: E1xuh9uoRYSNqi54KqgYCqAfyUfzhkYVjbNoU5xsxFKNm45YI8GEyEXkmgWTCgVrZztakiAnOhR0diw0xZn/wWVMyJs7f8LemqPqTq1EL4lRNh8wJ7WXb49d3L59C3xV7KEouOG5agqojyeqzhV+RqS4wtMN8ODkp7HCFLMi4AU5R4+sglRaZ+pSLwuuzXKlXiRdCm0YNpgb9NhmUl4gV0v7xVarpgX7C+aRTko2thIT+jm/YMxc+3TzCyPLmTNXqjKEgLcOQhUyezbhPYH4V9H4kAVPJ/WTV5iMLSZLrPpEYPucmjh5+OPPgKKYQ+PfIhS85jbFkEwZ8QTbjkBfOXn6ShMgFQtuRnVNIlBvd2FcZrpEUXOfO9CmNuLjXZRaw3MXfHuaz/uYtxuq8BhKHZbtGS24V70TneChGsJuNvqZLQ90v5sL7MlXkDldz0J0+DoFP39T0P00VfJUY3FxCrHHaTcguacGi1Et0MKe9sL0MIaldZjL0nKE4oQvoBCjeo9yMTu0kUWVKfDKyq7w83GlKiMbwKDuUMU4a0gQeugAStidgOrbmiXik8zO7o2gU+us6yRVYpxK2RyIL+zFsE6kAdv/pGUCn51IIRLJ+TYM5xDTmBt1fc7DjvtX+xVV0H8DwlwYUJhHn2P1jzh65dgIKav2Uz3+iXM6MuEu+sc=
  - secure: ulWu0roQrGBwDWD7ShJCprmF/WFu9Pcn/AB5DkBduzso0D/9W1uKrVQd96coKTieTGvMCC140LnUNQK4hnJKXOUPvFUc+DDMoy1wRTZtH6Hhw5lSXf7xb8uXX+VX/W3KxU34t0vARbIsryMapF4mIMHWrYowY4OlQiUURc4aBlqVrZi76f5RQM1hbye6qUFmQeYQmsjMybSO3WsP0Gk4+8Wi/VcKXRfH8SlIpu/75W5q1Y3JzEjLSww55kIWRAYbQS5eBpZKxn8bBWwWVh3Lt4tMjMjnUlUlh2KlY6LVIJC2kaQw1DwouGGJ9s0bzohZ1a0I7Yx5W2KfgB2jN68bfS5leJHwrXhVEdIvBi7dVgVVnqjRb+G/W9JZoO29yPc8Sjj3V5OGRTJ+QRkCMXrshayukKVOJIMx1gjjHxGCw015fM811UBB9A8EJfTZhP4pClnek1lliZXCInG9cILcn0onoVdoZMU4byughPvMNmhNZeBLRKuuUtvn0DciW+MhKcRxT46IQbbcwrlZ7LblYnrrN8eLfGgkZED5GdkZtY/PCOyg1zRWjYKypctsJcsd7xE7TCaqpz90LgZ1GX+SbwuDfYovs/i1TTYhGmFwYRa758pYIH1vGkuHFA2qbt3lbi59nvbkdIdBRHYYBG04lC1N31GGENut6hU884Iewaw=
  - secure: 0O8gDRa/bGJpGLf06y6S5xM9fgNkk5ZYqb2+6fQNFXHzAEkQUopXNDwAXuBtWL1XgCD4LVPJxv9nXC4xWm/dFnAPbmvKz8fzN3DZ6lgVpyKJI+PxBDCug98TZJhlP/AlqkypwiORHGsDkEC7nY/9RTpQv4gEdtwiKDiqPNM69tTcjijTd+9zdPcafsbijB5K7Ffis9I4aVosYLFXE0/lX2gFt5dNUtD6QRZmsL9MhxSyGVC5jsxJuFpndJhE06huM8m43kvp8D5ST+rmMpEFgP5yZg+7A5PUL1LUebQBWwNK7yt37S7ukKPPkMWK8xVCsy6paDfOqzEBsygPJi2AbRQQtMbV2W5BERWusUsivx7xLB7ldWBAP/Xnk6eszh1b8cUfeMCQPW3lONdBQgVs+ofD7JC2g8zrqMMY+9ORveSdXDyqpDQ3oHMu5Tok7M9uy4ScbcOQwf1TY7DHSCjj8lkf9YAnO6jK/MxYyAOGmV9q4U5boND3Ex7xET+ub5c/DOQlTt4C6CsE2NJBNxyR11c5hxq9zTqxz2kG8082YpAx7AHJJucGI6JcukF5ycj7MN16YbUj3wpc4F8YcKgXsSm78EK4jOdUvUl7vqa91Njh7DQ7DmbtYJCrQ4oakPzH+gO0ANimm+0sIsw+OGcCXgpPu/+wHQGkUF4C24cPKPI=
